// <auto-generated />
using ClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary.Migrations
{
    [DbContext(typeof(EmberContext))]
    partial class EmberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClassLibrary.Models.Ember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("epulet")
                        .HasColumnType("longtext");

                    b.Property<string>("iranyitoszam")
                        .HasColumnType("longtext");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pozicio")
                        .HasColumnType("longtext");

                    b.Property<string>("szallitas")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Emberek");
                });
#pragma warning restore 612, 618
        }
    }
}
